yihong0618/running_page

- scripts/keep_sync.py
> [keep sync] Check source instead of genre when generating gpx data because genre is not limited to KeepApp (eg. can be AppleWatch)

- .github/workflows/gh-pages.yml
- README-CN.md
- README.md
- gatsby-config.js
安装 workflow 后，下次更新 `master` 会触发自动部署到 GitHub Pages，默认 gh-pages 分支。
支持 2 种场景：
1. 使用自定义域名：workflow 中设置 fqdn
2. 使用项目目录：在 `gatsby-config.js` 设置 `pathPrefix`
> Add `Publish GitHub Pages` workflow

- .github/workflows/gh-pages.yml
- README-CN.md
- README.md
研究了 GitHub Actions 的文档，发现在 workflow 中使用 `secrets.GITHUB_TOKEN` 创建新的 commit，push 到仓库之后不会触发 workflow（为了防止无限死循环）。由于这个原因，执行完之前的 Sync Data workflow 之后，不会触发自动执行这一个 workflow。
可以通过使用用户级别的 GitHub user token 来来代替仓库级别的 GITHUB_TOKEN，避免这个问题，但是也会带来更多的配置步骤。
因此，为了方便，直接把这个 workflow 加进了定时任务，在 Sync Data 之后 5 分钟执行，省去了 token 的配置，应该能满足大部分用户的需求。
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
> Update GitHub Pages workflow with documentation

- scripts/codoon_sync.py
In previous version, timestamps in gpx is generated by a 5 seconds steps. 
This change it to use the artual timestamps in Codoon API.
> update Codoon gpx: use timestamp in points

- src/components/YearsStat/index.jsx
> 修复 YearsStat 组件中点击 Total YearStat 会出现两个Total YearStat (一上一下) 的 bug

- .github/workflows/gh-pages.yml
#106 
对这个 issues 讨论后，可以在 GitHub Action 中加一个复制命令，用来将静态的 svg 复制出来，便于使用自定义域名访问静态文件，
> feat: add copy svg copy command

- scripts/keep_sync.py
If synced with multiple source, for example, use both garmin
and keep record the workout, if we enable sync garmin in keep,
the result maybe doubled.
Use hte `isDoubtful` field to check the logs.
> Ingore doubtful activity from keep.

- requirements.txt
Garmin sync GitHub Actions run well until cloudscraper latest version `1.2.60` release 12 days ago. 
Look like the new version break on python `3.6`.
Setting to use last version `1.2.58` for now.  Test Passed.
If the problem won't fix with python `3.6` and the old version fail to bypass Cloudflare, maybe we have to upgrade to python `3.7`.
> fix: cloudscraper 1.2.60 break on python 3.6, use 1.2.58 instead

- scripts/config.py
Use reletive path to solve the problem #229 with `unable to open database file` when run scripts from `scripts` folder.
Tested works when running scripts both from `ContentRoot` or `ContentRoot/scripts` folder on Windows environment.
> fix: "unable to open database file" when run scripts from `scripts` folder

- .dockerignore
- Dockerfile
- package.json
1. `dockerfile` should use it's cache properly, build docker image would fast than ever before.
2. `build` and `serve` flow in `package.json` use `--prefix-paths` as default, option `pathPrefix` in `gatsby-config.js` should be setting manually. (NOTE: if adopting this commit "83f23413a03afdac33607afff92aecca97642480", `gatsby-config.js`'s  `pathPrefix` should be annotated? I'm not familiar with front-end QAQ), it just a workaround for me by using `nginx`'s redirects to `docker`)
> optimize docker workflow

- scripts/keep_sync.py
keep use gcj02 coordinate system, while Mapbox use wgs84 coordinate system, add coordinate transform after running points retrived.
Code reference: https://github.com/wandergis/coordTransform_py
> add coordinate trans for keep sync

- scripts/generator/db.py
The healthfit synced Apple Watch record to Strava but no `summary_polyline`.
```
Run python scripts/strava_sync.py *** *** ***
Access ok
Start syncing
something wrong with 7796808006
'NoneType' object has no attribute 'summary_polyline'
.something wrong with 7804774185
'NoneType' object has no attribute 'summary_polyline'
.something wrong with 7817409219
'NoneType' object has no attribute 'summary_polyline'
.
```
> fix: no attribute 'summary_polyline'

- .github/workflows/ci.yml
- .github/workflows/gh-pages.yml
- .github/workflows/run_data_sync.yml
GitHub deprecated set-output command, recommend using GITHUB_OUTPUT environment file instead:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Current warnings in [CI](https://github.com/yihong0618/running_page/actions/runs/3238756532/jobs/5307320860):
> Replace deprecated set-output command

- .github/workflows/run_data_sync.yml
- README-CN.md
- README.md
For those who use Garmin auto-sync job and do `Sync fork` action, you need to set the right sercets:
*  `GARMIN_EMAIL` instead of `GRAMIN_EMAIL`
*  `GARMIN_CN_EMAIL` instead of `GRAMIN_CN_EMAIL`
> fix: typo (warning: would cause `data sync` job to fail for Garmin user, re-config `secret` is needed)

- scripts/gpxtrackposter/track_loader.py
`track_loader` would merge activities within 1 hour, but it didn't consider the `type`.
In some cases, eg. in Triathlon, people swimming/cycling/running in a row. 
I've added the condition for the same type. This feature is important for `workouts_page` users but maybe is not that important for `running_page` users, close this PR if you think that.
> fix: avoid merging for different types

- src/components/RunMap/index.jsx
A bug was introduced for dependency '@mapbox/mapbox-gl-language' upgraded to 1.0.0
This causes Mapbox Chinese not to show properly, I did a little refactoring to suit the package upgrade.
* Adds support for Mapbox Streets v8 vector tileset and all styles based on this tileset, such as streets-v11 and dark-v10 while removing support for Mapbox Streets v7 vector tileset-based styles. 
* upgrade dark-v9 -> dark-v10
* Support for Streets v7 Chinese zh is replaced with Traditional Chinese zh-Hant and Simplified Chinese zh-Hans. 
* `zh` -> `zh-Hans`
ref: https://github.com/mapbox/mapbox-gl-language/releases/tag/v1.0.0
> fix: Mapbox 'zh' is not working while package 'mapbox-gl-language' upgraded

- scripts/garmin_sync.py
解决佳明数据同步出现402 Client Error: Payment异常问题
> fix: 解决佳明数据同步出现402 Client Error: Payment异常问题

- Dockerfile
python:3.10.5-slim image does not have git package installed, so pip install will fail by git+https://github.com/alenrajsp/tcxreader.git
> fix: python:3.10.5-slim image not has git

- src/components/Layout/style.module.scss
- src/components/RunMap/RunMapButtons.jsx
- src/components/RunMap/index.jsx
- src/components/RunMap/style.module.scss
- src/components/RunTable/RunRow.jsx
- src/components/RunTable/index.jsx
- src/components/RunTable/style.module.scss
- src/components/SVGStat/index.jsx
- src/components/Stat/index.jsx
- src/components/YearStat/index.jsx
- src/pages/index.jsx
- src/styles/index.scss
原本看到 Total 视图中给每个 `<react>` 和 `<polyline>` 都监听了 `click` 事件，数量极多，就用事件代理方式重构了一下，但影响到 `locateActivity` 方法在 `<RunRow>` 的调用，所以将 `locateActivity` 统一都改用 `runDate` 作为入参，最终由于关联改动的文件有 12 个，所以作为了一个提交。
主要调整如下：
1. 使用事件代理的方式重构 /pages/index.jsx 下有关 `<rect>` 和 `<polyline>` 的点击事件。
2. 调整 `locateActivity` 方法的入参为 `runDate`，仅在此方法被调用时从 `runs` 中查询当前 `run`。
3. 重构 `<RunMapButtons>`，使用 `className` 简化高亮年份，去除不必要的 `indexOf` 查找下标动作。
4. 在 `<RunRow>` 组件中使用 `className` 来高亮被点击的行，避免使用 `getElementsByClassName` 方式查询多余 tr 节点，提高性能。
5. 修复：当点击右侧列表某行后再点击左侧年份，右侧列表高亮行未消失，以及地图左下角的标题未更新。
修复前：
修复后：
6. 去除 ``<Stat value={`${streak} day`}`` 中无用的 className="mb0 pb0" 声明，`<Stat>` 组件设置 `className` 默认值为 "pb2 w-100"，避免渲染时出现 `undefined`。
7. 去除 `<RunMap>` 和 `<RunTable>` 组件的 `mapButtonYear` `runs` `year` 等无用属性。
> refactor: use event delegation to handle all <rect> & <polyline> in the "Total" view.

- README-CN.md
- README.md
- requirements.txt
- scripts/garmin_device_adaptor.py
- scripts/garmin_sync.py
- scripts/strava_to_garmin_sync.py
添加Garmin设备信息的主要目的是使得可以通过Garmin间接得将运动记录同步到其他不支持Apple Watch的运动APP中，
比如`数字心动（上马）`，当然添加了设备信息之后，这些运动记录也可以同步运动记录到Keep，悦跑圈，咕咚等，但是需要注意在这些APP中，如果同时使用Apple Watch同步和Garmin同步的记录可能会重复。
- 在strava_to_garmin_sync脚本中增加是否使用自定义Garmin设备的选项`--use_fake_garmin_device`，不加这个参数表示不启用
- 默认的Garmin设备的序列号是`1234567890`，Garmin 会将这个序列号识别为`Forerunner 245`，如果要更改设备，需要先获取真实Garmin设备序列号，在`garmin_device_adaptor.py`中修改 `GARMIN_DEVICE_SERIAL_NUMBER`的值
> [FEAT] add garmin device in strava_to_garmin_sync 

- src/components/Header/index.jsx
- src/components/Layout/index.jsx
- src/components/LocationStat/index.jsx
- src/components/RunMap/RunMaker.jsx
- src/components/RunMap/RunMapButtons.jsx
- src/pages/index.jsx
1. 使用 `<></>` 替换 `<Header> <Layout> <RunMarker>` 组件根结点，以提升渲染性能。
2. 去除非必要的 `<div>` 标签。
3. 发现主体布局使用了 float，但未清除。使用 clearfix，以确保主体 `<div>` 渲染出正常高度。
清除浮动前
清除浮动后
> chore: use <></> & remove unnecessary tags & clear float

- .github/workflows/run_data_sync.yml
- README-CN.md
- README.md
- requirements.txt
- scripts/generator/__init__.py
- scripts/gpxtrackposter/track.py
- scripts/polyline_processor.py
**Little privacy enhancement**
Adding 4 environment variables to support hiding area for polyline start end and chosen points.
Using [this](https://developers.google.com/maps/documentation/utilities/polylineutility) to making `IGNORE_POLYLINE`.
```shell
IGNORE_START_END_RANGE = 200 # ignore meters for each polyline start and end.
IGNORE_RANGE = 200 # ignore meters for each point in the below polyline. 
IGNORE_POLYLINE = ktjrFoemeU~IorGq}DeB # a polyline include point you want to ignore. 
IGNORE_BEFORE_SAVING = 1
```
> feat(privacy): support hiding polyline start, end and choosing points

- README-CN.md
- README.md
- scripts/config.py
- scripts/garmin_sync.py
add parameter `--fit` to support download Garmin fit file
> feat:support for download Garmin fit file

- scripts/codoon_sync.py
Change "Run" to "Running" so when uploading the TCX files to Strava, it won't be recognized as "Ride".
> Fix Sports Type in codoon_sync.py

- .github/workflows/ci.yml
- .github/workflows/gh-pages.yml
- .github/workflows/run_data_sync.yml
- README-CN.md
- README.md
1. run_data_sync 调用 gh_page方式改成了workflow_call，这样可以传递一些数据过去。可以把设置都放在run_data_sync env中完成。在github后台看来也在一个job中完成了。
2. 缓存默认关闭，添加了文档。
3. 三个workflow中的action版本做了升级。有好几个github action提示版本过低了。
4. python和node准备环境部分做了优化。用了setup python /setup node自带的cache参数。多余的几个step删了。
> 添加保存过程中产生的数据文件到github action cache选项，顺便重新整理了一下github aciton workflow

- scripts/gpxtrackposter/grid_drawer.py
- scripts/gpxtrackposter/track.py
- src/components/RunTable/RunRow.jsx
- src/pages/index.jsx
如果同一天有多条运动记录时，从列表、路线缩略图及日期方块选择纪录，地图会显示错误的路线。
具体讨论可以查看：
[https://github.com/ben-29/workouts_page/issues/17](https://github.com/ben-29/workouts_page/issues/17)
[https://github.com/ben-29/workouts_page/pull/18](https://github.com/ben-29/workouts_page/pull/18)
> fix: 同一天有多个运动时选中地图路线显示错误问题

- .github/workflows/gh-pages.yml
- README-CN.md
- README.md
should fix https://github.com/yihong0618/running_page/discussions/480
> fix: gh-pages to Actions and fix the path bug

- .vercelignore
- package.json
- pnpm-lock.yaml
- src/components/Layout/index.tsx
- src/components/RunMap/RunMaker.tsx
- src/components/RunMap/index.tsx
- src/components/RunMap/mapbox.css
- src/components/RunMap/style.module.scss
- src/components/RunTable/index.tsx
- src/pages/index.tsx
- src/utils/utils.ts
This commit do these things,
cause react update to 18 there is a serious bug for react-map-gl, so we deside to update it to v7.
for v7 there's a lot of break change, we fix them as follows:
- bring mapbox css to the file.
- change the api that break
- add two packages in it to fit the change
- change viewport name to viewState to fit the api change
> fix: v2.0 can not zoom

- run_page/keep_sync.py
之前对于没有成功获取到gpx的跑步记录会抛出异常，导致该跑步记录导出失败；
现在不再抛出异常，保证跑步记录可以被导出，不过导出的跑步记录没有gpx。
> #484 导出keep接口升级无法获取gpx数据的跑步记录

- requirements.txt
- run_page/keep_sync.py
> fix: #484 keep gps data decode

- run_page/gpxtrackposter/utils.py
When rendering the grid.svg, it will display all polylines in the `grid.svg`. However, a route can be quite large. For example, a marathon may contain thousands of data points, which is just one running record. Nevertheless, the polyline in the SVG does not need to be overly precise.
I have added a `zoom_threshold` to control whether to omit some data points when the length is too long. This threshold ensures that the length of each polyline remains below the specified value.
In my case, before this change, my grid.svg was 10.9MB and after reducing it became 3.6MB.
Increase this parameter if you want fewer affected polylines. Decrease it if you want a smaller SVG file.
Note: This change primarily affects track running because it drops data points between circles. Therefore, data points …
> feat: reduce grid svg file size

- .github/workflows/gh-pages.yml
When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.
If build GitHub page from Run Data Sync,  it may be outdated. And user needs to run the action again to build from the latest commit.
see: https://github.com/actions/checkout#usage
> fix: gh-pages build: drop the ref while trigger from Run Data Sync

- vite.config.ts
Splitting activities.json from index-xxx.js to improve the initial loading experience.
The left side of the image is the split part.
> perf: split `activities.json` from index

- src/pages/index.tsx
update the year when change by Title & City, otherwise the `SVG` will be displayed and the table will not be shown if the previous status is 'Total'
> fix: total state SVG

- run_page/codoon_sync.py
- run_page/utils.py
> fix: Codoon tcx output use start_time as ID instead of Codoon id

- run_page/garmin_sync.py
When an activity is uploaded to Garmin Connect in a .gcx file, the downloaded raw activity zip file can be unzipped to a .gcx file rather than .fit file. In this way, the script crashes for absence of `f"{activity_id}_ACTIVITY.fit"`. In this PR, I simply deleted it if it is not a .fit. Actually it also makes sense if we reserve the .gpx and sync/generate running page in code logic for .gpx.
> Fix: crash if unzipped file is .gcx format

- requirements.txt
- run_page/garmin_device_adaptor.py
- run_page/garmin_sync.py
- run_page/gpxtrackposter/track.py
- run_page/gpxtrackposter/utils.py
using Garmin official sdk to read fit file, fixing #584
> fix: #584 change fit-tool to garmin-fit-sdk

- README-CN.md
- README.md
- src/components/RunMap/LightsControl.tsx
- src/components/RunMap/index.tsx
- src/components/RunMap/style.module.scss
- src/utils/const.ts
Add a light switch button, when turned off, displays only the routes and blacks out the entire map. These features come with some other changes.
1. In the Easter Egg map, display both the China boundary and the running routes, not just the China boundary.
2. In lights-off mode, turn off dash lines and line transparency, and enhance the line to emphasize the route.
> Feat: lights switch

- run_page/generator/db.py
The frontend only parses country name in Chinese. Without this PR, `location_country` is in local language (French in France, Deutsch in Germany), which causes the frontend unable to resolve country count.
With this PR, issue #597 is fixed.
> fix: resolve issue #597

- src/components/SVGStat/index.tsx
- src/components/YearStat/index.tsx
- src/utils/svgUtils.tsx
Before
When hovering over the `YearStat` component, the page crashes if the `./year_${year}.svg` file is not found.
<details>
<summary>Error call stack</summary>
TypeError: yearStats[year] is not a function
at http://localhost:5173/src/components/YearStat/index.tsx?t=1705334672175:30:42
at lazyInitializer (http://localhost:5173/node_modules/.vite/deps/chunk-5HQCJSLF.js?v=dfc8bfd7:869:28)
at mountLazyComponent (http://localhost:5173/node_modules/.vite/deps/chunk-S3R3ZQRI.js?v=dfc8bfd7:14817:27)
at beginWork (http://localhost:5173/node_modules/.vite/deps/chunk-S3R3ZQRI.js?v=dfc8bfd7:15906:22)
at beginWork$1 (http://localhost:5173/node_modules/.vite/deps/chunk-S3R3ZQRI.js?v=dfc8bfd7:19749:22)
at performUnitOfWork (http://localhost:5173/node_modules/.vite/deps/chunk-S3R3ZQRI.js?v=dfc8bfd7:1919 …
> fix: svg not found causes page crash

- run_page/joyrun_sync.py
修正转化gpx时，暂停导致的时间记录错误，按照gpx格式给每个暂停的跑步片段分配给各个segment
> Joyrun gpx export fix for pauses and gpx segments

- src/components/LocationStat/index.tsx
Mention here: 地图缩放的时候 LocationStat 和 YearsStat 文字会稍微跳动一下 #603
> fix: text position change when map zoom in and zoom out

- .github/workflows/ci.yml
[The recent GitHub Actions](https://github.com/yihong0618/running_page/actions/runs/7722942807) shows deprecation annotation saying they have changed [Node.js 16 to 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.)
The ci.yml file is updated In this PR:
- Upgrade checkout to v4 from v3
- Upgrade setup-python from v4 to v5
> Update actions version in ci.yml

- .github/workflows/gh-pages.yml
- .github/workflows/run_data_sync.yml
- README-CN.md
- README.md
In this PR, the following items are updated:
1. Updated .github/workflows/gh-pages.yml:
- actions/checkout from v3 to v4
- actions/cache from v3 to v4
- actions/setup-node from v3 to v4 with node-version from 18 to 20
- actions/upload-pages-artifact from v1 to v2
- Note: v3 and v4 are incompatible with actions/upload-artifact@v3, [which currently do not support on GHES](https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new)  
- actions/deploy-pages from v1 to v3
1. Updated .github/workflows/run_data_sync.yml:
- actions/checkout from v3 to v4
- actions/setup-python from v4 to v5
- actions/cache from v3 to v4
1. Updated README:
- Updated Yer1k's running page link
- Added instructions for people who would like to deploy their running page on GitHub.io with custom …
> Update GitHub Actions and README

- .vercelignore
- package.json
Fix issue vercel error: spawn pip3 ENOENT by:
- Update packageManager field from "pnpm@8.7.0" to "yarn@1.22.22"
- Add `requirements-dev.txt` to `.vercelignore`
close: #627
@ben-29 can you help to review, maybe workouts_page also need this
> chore: Update package manager and ignore requirements-dev.txt

- Dockerfile
- README-CN.md
- README.md
1. https://registry.npm.taobao.org has been expired, use https://registry.npmjs.org/.
2. add proxy config for someone who needed.
3. Use yarn instead of pnpm(Has some fault when build docker).
4. Add Keep config.
> Add proxy config, add keep config, change npm registry, use yarn

- .github/workflows/run_data_sync.yml
- README-CN.md
- run_page/keep_sync.py
- run_page/keep_to_strava.py
- run_page/keep_to_strava_sync.py
Only provide the ability to sync data from Keep's multiple sport types to Strava's corresponding sport types, to help those who use multiple devices like me. The web page presentation still uses Strava (or refer to nike_to_strava_sync.py to modify it to suit you). #167 #478 #600 #62 #646 #172 
Specifics:
1. download data from Keep for running, cycling and hiking sport types and generate gpx without intruding into data.db and activities.json.
2. Upload to Strava, automatically recognised as the corresponding sport type (running, cycling, hiking).
3. some fields in the successfully uploaded sports data are logged in activities/keep2strava.json (in order to keep track of whether they have been uploaded or not).
4. Remove the corresponding gpx.
My own best practices:
1. running/hiking …
> add keep2strava

- .github/workflows/gh-pages.yml
Fix the following warnings:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: pnpm/action-setup@v2, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "github-pages".
Please update your workflow to use v4 of the artifact actions.
Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> fix the deprecation warning

- README-CN.md
- run_page/joyrun_sync.py
To resolve #675 
By `subprocess.run` to serial start process.
Tried to investigate integrate `gen_syg` as module, but `sys.argv` must be updated before invoking `gen_svg.main()`. Repeatedly constructing `sys.argv` 3 times is not elegant to me.
Verified locally
- with 2 new options
- without 2 new options
- with only `--athlete`
- with only `--min_grid_distance` // same behavior with without 2 new options is as expected
Ran `black .` but only kept changes by this commit.
> feat: integrate gen_svg into joyrun_sync.py(#675)

- README-CN.md
- README.md
- run_page/nike_sync.py
(cherry picked from commit 06202c324b97e0407a0a871178ea150080a64c81)
> new way to sync nrc

- README-CN.md
- README.md
The document is missing a closing tag, causing content after  "Nike Run Club" to be invisible.
> Fix readme tag closure

- run_page/keep_to_strava_sync.py
Corrected import in `keep_to_strava_sync.py` to use `KEEP_SPORT_TYPES` instead of `KEEP_DATA_TYPE_API`.
> fix: use `KEEP_SPORT_TYPES` instead of `KEEP_DATA_TYPE_API`

- run_page/gpxtrackposter/poster.py
adding illustration for special tracks based on input special distance
> feat: adding illustration for special tracks 

- package.json
- run_page/keep_sync.py
- src/utils/utils.ts
hi , yihong
I export  some keep records , almost indoor run data  🫣. 
the geoPoints is empty or looks incomplete decoded data, 
i prefer the bounds is dalian(from location_country) not beijing.
btw the part of the keep data is : 
```
{
"run_id": 9223370384358951307,
"name": "VirtualRun from keep",
"distance": 7095.168620939273,
"moving_time": "21:28:40",
"type": "VirtualRun",
"start_date": "2022-05-13 05:08:24",
"start_date_local": "2022-05-13 13:08:24",
"location_country": "{'latitude': 38.858706, 'longitude': 121.52418, 'country': '\u4e2d\u56fd', 'nationCode': '156', 'province': '\u8fbd\u5b81\u7701', 'city': '\u5927\u8fde\u5e02', 'cityCode': '0411', 'district': None, 'districtCode': None, 'startLatitude': 0.0, 'startLongitude': 0.0}",
"summary_polyline": "gqqrFsrkeU??", // or null …
```
> Some Front Optimization for Keep indoor data

- run_page/generator/__init__.py
When enable IGNORE_BEFORE_SAVING, workflow run failed:
```
Run python run_page/strava_sync.py *** *** ***
Traceback (most recent call last):
File "/home/runner/work/workouts_page/workouts_page/run_page/strava_sync.py", line 33, in <module>
Access ok
run_strava_sync(
File "/home/runner/work/workouts_page/workouts_page/run_page/strava_sync.py", line 14, in run_strava_sync
generator.sync(False)
File "/home/runner/work/workouts_page/workouts_page/run_page/generator/__init__.py", line 68, in sync
activity.summary_polyline = filter_out(activity.summary_polyline)
AttributeError: 'Activity' object has no attribute 'summary_polyline'
Start syncing
Error: Process completed with exit code 1.
```
Sorry, this is my first time using PR. 
I accidentally submitted my own changes just now. I created a new …
> Fix AttributeError in Activity class

- run_page/gen_svg.py
- run_page/gpxtrackposter/github_drawer.py
- run_page/gpxtrackposter/year_range.py
> ignore the year which has no running data when drawing github.svg

- src/pages/index.tsx
- vite.config.ts
In non-Vercel deployment environments(Github Pages), there will be a 404 request for the Vercel Analytics JS.
After modification, output under Vercel deployment:
output non-Vercel deployment:
> feat: conditionally output analysis JS only in Vercel environment

- README-CN.md
- README.md
- run_page/gpxtrackposter/track.py
- run_page/joyrun_sync.py
- run_page/keep_sync.py
- run_page/nike_sync.py
- run_page/nike_to_strava_sync.py
- run_page/oppo_sync.py
> feat: fix nrc Changed their apis

- src/components/RunMap/index.tsx
When my browser is already fullscreen, clicking `FullscreenControl` the map doesn't fill the entire screen.
- before
https://github.com/user-attachments/assets/26c83240-dac6-415c-a430-e6a579069259
- after
https://github.com/user-attachments/assets/820d130f-cb57-4c6a-b7f7-78411f080d52
> fix: `FullscreenControl` is not fullscreen until resizing window

- src/components/RunMap/index.tsx
[Related PR](https://github.com/yihong0618/running_page/pull/726)
When `onRender` calls resize, resize will not be triggered. Instead, listen for `fullscreenchange`
> perf: listen to `fullscreenchange` instead of `onRender` resize

- run_page/gpxtrackposter/tracks_drawer.py
- issue [Total 统计图 格子颜色不对](https://github.com/yihong0618/running_page/issues/725)
- Because there are two special distances, when there is only one, `interpolate_color` is wrong. The solution is to check whether `special_distance2` is greater than `length_range.upper()`. If it is greater, return `color1`
> fix: tracks color

- run_page/garmin_sync_cn_global.py
- run_page/synced_data_file_logger.py
In the previous version, the synced_activity.json is not stored in the github actions cache. In this commit, it no longer relies on the synced_activity.json but gets downloaded_ids directly from FIT_OUT and GPX_OUT in the same way with garmin_sync.
> fixed a bug where incremental uploads failed

- README-CN.md
- README.md
Python 3.7 does not work properly in Cloudflare, whereas Python 3.11 does.
> Python 3.7 to 3.11 in Cloudflare

- .github/workflows/run_data_sync.yml
- requirements.txt
- run_page/save_to_parqent.py
you can use duckdb pargent
pip3 install duckdb
```python
import duckdb
duckdb.sql("select regexp_extract(location_country, '[\u4e00-\u9fa5]{2,}(市|自治州|特别行政区)') as run_location, concat(try_cast(sum(distance/1000) as integer)::varchar,' km') as run_distance from read_parquet('https://github.com/yihong0618/run/raw/refs/heads/master/run_page/data.parquet') where run_location is not NULL group by run_location order by sum(distance) desc;").show(max_rows=50)
```
show
```cli
┌──────────────┬──────────────┐
│ run_location │ run_distance │
│   varchar    │   varchar    │
├──────────────┼──────────────┤
│ 大连市       │ 9328 km      │
│ 沈阳市       │ 2030 km      │
│ 北京市       │ 61 km        │
│ 长沙市       │ 24 km        │
│ 扬州市       │ 21 km        │
│ 盘锦市       │ 21 km        │
│ 烟台市       │ 21 km …
```
> feat: pargent

- run_page/joyrun_sync.py
and support user-defined threshold value in command line.
1. 同步悦跑圈数据时，移除重复记录（当用华为手表开启了同步悦跑圈会出现该情况）。重复记录的默认定义：起时间相差10s
2. 当遇到重复记录时，保留 distance 更长的记录。
3. 在命令行支持 `threshold` 参数，指定如何定义重复。
> Remove duplicate runs from joyrun

- run_page/joyrun_sync.py
```
Traceback (most recent call last):
File "/home/runner/work/running_page/running_page/run_page/joyrun_sync.py", line 399, in <module>
tracks = j.get_all_joyrun_tracks(
^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Joyrun.get_all_joyrun_tracks() takes from 2 to 3 positional arguments but 4 were given
```
add `threshold` argument with default value
> fix: `get_all_joyrun_tracks` arguments not match error

- Dockerfile
现有的版本的Dockerfile在build的时候报错如下：
```
=> ERROR [develop-node 5/5] RUN npm config rm proxy&&npm config set registry https://registry.npmjs.org/   &&npm install -g corepack   &&corepack enable   &&yarn install                                                                          1.7s
------                                                                                                                                                                                                                                                   
> [develop-node 5/5] RUN npm config rm proxy&&npm config set registry https://registry.npmjs.org/   &&npm install -g corepack   &&corepack enable   &&yarn install:                                                                                     
1.365 …
```
> fix Dockerfile: package manager from yarn->pnpm

- .github/workflows/run_data_sync.yml
- run_page/gen_svg.py
- run_page/gpxtrackposter/github_drawer.py
- run_page/gpxtrackposter/poster.py
github 的 年度图已经是从第一天开始绘画，会跳过第一周但是非本年的日子， 如下图
本次修改从 向上一年补齐格子的逻辑改成了跳过格子，从每年的第一天开始绘画
修改前：
修改后：
> chore: 优化 github_svg 生成，从每年第一天开始

- .github/workflows/ci.yml
- .github/workflows/run_data_sync.yml
**问题背景** 
在 GitHub Actions 工作流中，当尝试执行 `git push` 时，遇到以下错误：  
`fatal: could not read Username for 'https://github.com': No such device or address`  
经排查，此问题是由于 `actions/checkout@v4` 默认关闭了凭据持久化 (`persist-credentials: false`)，导致后续 Git 操作无法自动使用 `GITHUB_TOKEN` 认证。
**改动内容**  
- 在 `actions/checkout` 步骤中显式设置 `persist-credentials: true`。  
- 此配置会保存 `GITHUB_TOKEN` 凭据，确保后续 `git push` 操作通过认证。  
**测试结果**  
- 修改后，工作流成功推送更改至仓库 [Run Data Sync · viazure/running_page@d82985d](https://github.com/viazure/running_page/actions/runs/13351482128)）。
> fix: Enable persist-credentials to resolve authentication failure in GitHub Actions

- run_page/joyrun_sync.py
The duplicate check #757 logic should exclude the track generation part to avoid unnecessary track generation processes.
> fix: joyrun duplicate check logic

- run_page/joyrun_sync.py
For JoyRun GPX output file, add heart rate data in the Garmin TrackPointExtension schema.
The heart rate data is not one-to-one mapping to the coordinate data. Use best effort to add heart rate data in extension for GPX files.
> [Add] Add heart rate data in Joyrun output GPX file extension

- src/utils/const.ts
- src/utils/utils.ts
Set the color of activity path based on the newly added `type` and `subtype`. FYI plz visit https://run.zhengnq.com
Credits to @ben-29's workouts page.
> [feat] Different path color based on sport type

- run_page/generator/db.py
fix below error
```log
something wrong with 1084242294
float() argument must be a string or a real number, not 'NoneType'
```
> fix: handle None values for elevation gain in activity updates

- run_page/gpxtrackposter/track.py
fix issue: #851
> When a Garmin GPX file is loaded into data.db, the "type" field is stored as "running". However, many features — such as the summary page — expect the type to be "Run", so they do not work correctly.
> bugfix: fix wrong "type" value when load Garmin gpx file.

- src/hooks/useActivities.ts
Fixed https://github.com/yihong0618/running_page/issues/782
The root cause is the inconsistency in country names between activity file and mapbox layers. For example, USA in activity file will be "美利坚合众国/美利堅合眾國" but only "美国" works for mapbox. Another example is "英国 / 英國" and "英国".
The function `standardizeCountryName` can be extended to other countries later.
> Fix inconsistency between activity file and mapbox layer in country name

- .github/workflows/run_data_sync.yml
- README-CN.md
- README.md
- run_page/strava_to_garmin_sync.py
recently [stravaweblib](https://github.com/pR0Ps/stravaweblib/blob/fd5f6c9e87fc43afd81dd434c15d9c09f73ba0cb/stravaweblib/webclient.py#L123) login failed via username and password, see https://github.com/yihong0618/running_page/issues/862 ,  so a new strava JWT way was provided to download original strava activity file like FIT or TXC file.
how to use:
```bash
python run_page/strava_to_garmin_sync.py ${{ secrets.STRAVA_CLIENT_ID }} ${{ secrets.STRAVA_CLIENT_SECRET }} ${{ secrets.STRAVA_CLIENT_REFRESH_TOKEN }}  ${{ secrets.GARMIN_SECRET_STRING }} ${{ secrets.STRAVA_EMAIL }} ${{ secrets.STRAVA_PASSWORD }} ${{ secrets.STRAVA_JWT }} 
```
the JWT can be found in `strava_remember_token` in Cookie.
finally it works.
> fix strava sync garmin failed

- src/components/RunMap/index.tsx
- src/utils/utils.ts
It allows users to scroll the page over the map on the touch devices and remains original logic on other devices.
On the touch devices, users can use two fingers to pan or zoom the map.
> feat: Allow users to scroll the page over the map on touch devices

- run_page/gpxtrackposter/track_loader.py
Fix #888 .
As titled.
It's common that two activities has start_time less than one hour.
> fix: Remove activity merging for start times within one hour

- run_page/coros_sync.py
1. Add support for gpx and tcx file format.
2. Fix: Default values are incompatible due to varying type values across sport types.
```python
download_url = f"{COROS_URL_DICT.get('DOWNLOAD_URL')}?labelId={label_id}&sportType=100&fileType=4"
```
> feat: support gxp and tcx file for Coros.

- README-CN.md
- README.md
- run_page/gpxtrackposter/github_drawer.py
- add `--empty-data-color` parameter for generating svg images for light theme.
> feat: add customizable color for empty dates in GitHub style poster

- run_page/coros_sync.py
- run_page/gpxtrackposter/track.py
fix #896 
Automatically remove incomplete or corrupted FIT files when network connectivity is unstable or interrupted during transfer. This activity can be downloaded next time.
> feat: delete corrupted fit files on network instability.

- src/components/YearStat/index.tsx
- src/hooks/useHover.ts
- Change the binding element of the mouseover area to avoid `hr`
- Use `timerRef` to store the id of the `setTimeout` so that rendering is not repeatedly triggered when the mouse moves in and out quickly.
- Change the trigger time of svg to 1000 ms.
> refactor: optimize mouse-over effect for year images

- run_page/garmin_sync.py
Closes #971
Fixed an issue where the add_summary_info function would cause an XML error when parsing non-GPX files (like .fit). This was resolved by adding and file_type == "gpx" to the call condition.
> fix: Prevent add_summary_info from processing non-GPX files (#971)

- run_page/strava_sync.py
The `sync_types` parameter was introduced in PR #923, but its default value causes `only_run` to be set to true.
```
def run_strava_sync(
client_id,
client_secret,
refresh_token,
sync_types: list = ["running"],
only_run=False,
):
generator = Generator(SQL_FILE)
generator.set_strava_config(client_id, client_secret, refresh_token)
->    if not only_run and len(sync_types) == 1 and sync_types[0] == "running":
only_run = True
```
This would cause all scripts that do not pass this parameter, including `strava_sync.py` itself, to only sync the Run type.
fix https://github.com/ben-29/workouts_page/issues/50
> fix: strava_sync forced to only_run

- run_page/strava_sync.py
The last PR introduced a bug; change the default to an empty list instead of `None` to prevent errors caused by `len(None)`.
> Fix strava sync Error

- src/hooks/useActivities.ts
Revise country name conversion into a more flexible way. Fix Indonesia nameing inconsistency.
> fix naming inconsistency between activity and mapbox data

- .gitignore
- run_page/codoon_sync.py
> fix: Codoon export KeyError
