README-EN.md, README.md
=> update README and README-EN

.github/workflows/run_data_sync.yml
:wrench: add github action manual trigger
=> add github action manual trigger

.gitignore, .vscode/settings.json, README-EN.md, README.md, config-example.yaml, package.json, requirements.txt, scripts/config.py, scripts/garmin_sync.py
Major changes:
- Use asyncio, remove multithread, limit concurrent downloads to avoid exhaust connection pool or hit server limitation
- Add loading configuration from file (config file is optional, command line parameters still take precedence)
- Remove unused code
- Format python code with ~~yapf~~ black
=> Improve Garmin sync

src/utils/utils.js
拉取 App 数据为空时，导致页面构建失败。
```js
// src/static/activities.js
const activities = [];
export {activities};
```
=> fix: default boundary error

README-EN.md, README.md, src/utils/utils.js
=> update Province regex

src/utils/utils.js
refactor sortDateFuncReverse to reuse sortDateFunc rather than repeat the same logic
=> refactor sortDateFuncReverse

scripts/keep_sync.py
fix for keep import when no heart beat information available.
=> fix for keep import when no heart beat information available.

README-CN.md, README.md
=> add: new runner

scripts/nike_to_strava_sync.py
=> fix: new_gpx_files might be None

scripts/gpxtrackposter/track.py
track_loader._merge_tracks: merge tracks that took place within one hour
will call track.apend
this change will also update moving_dict and  polylines fields in track
=> Pr merge tracks

README-CN.md, README.md
=> change running platform

README-CN.md, README.md
=> add new runner to README

README-CN.md, README.md
Add my page to  "Runner's Page Show" , thanks your project !
=> update readme.md, add my running page

README-CN.md, README.md
=> Add MFYDev's running page

README-CN.md, README.md
1. Change MFYDev's data source from Nike to Garmin;
2. Add notes about the possible Nike Run Club 403 error, please refer to issue https://github.com/yihong0618/running_page/issues/126
=> 2 minor changes to README.md

src/components/Layout/index.jsx
=> 修复 title 不显示的问题

scripts/nike_sync.py
fix https://github.com/yihong0618/running_page/issues/141
=> nike sync: ignore NTC record 

scripts/nike_sync.py
如题，使用 keep 导出的gpx文件类似下图，这段逻辑是有问题的。
=> fix an issue when mixed keep & nike gpx files

src/utils/const.js, src/utils/utils.js
由于我之前一直用的自己定义的跑步名称，所以没有发现这里有点小问题。
Morning 的话严格来讲11点之前都算，Lunch Run 感觉叫做 Midday Run 更加合适，连带着时间也改了一小下。
这个还是需要 @yihong0618 来审核一下，要是可以就改一下
=> Fix translation and time

README-CN.md
=> Add @oysmart's running page

scripts/codoon_sync.py, scripts/utils.py
This pr does 3 things about codoon_sync.py
1.  add login fail exception
2.  add type to gpx
3.  using utc time in gpx, fix #159
=> Codoon fix time

scripts/codoon_sync.py
=> update scripts/codoon_sync.py import util

README-CN.md, README.md, src/components/RunMap/index.jsx, src/utils/const.js
=> style: dash-line(optional), opacity

src/components/RunMap/index.jsx
https://github.com/yihong0618/running_page/pull/205#issuecomment-1039843984
using normal line in Single
=> style: dash-line, disable in single run

.vscode/settings.json, README-CN.md, README.md
=> doc:clean up the readme file

.github/workflows/ci.yml, .github/workflows/run_data_sync.yml, README-CN.md, README.md, requirements-dev.txt, requirements.txt, scripts/codoon_sync.py, scripts/config.py, scripts/endomondo_sync.py, scripts/garmin_sync.py, scripts/garmin_to_garmin.py, scripts/gen_svg.py, scripts/generator/__init__.py, scripts/gpx_sync.py, scripts/gpxtrackposter/track.py, scripts/gpxtrackposter/track_loader.py, scripts/gpxtrackposter/utils.py, scripts/joyrun_sync.py, scripts/keep_sync.py, scripts/nike_sync.py, scripts/nike_to_strava_sync.py, scripts/strava_sync.py, scripts/tcx_sync.py, scripts/tcx_to_strava_sync.py, scripts/utils.py
1. support `tcx`
2. garmin can download files as `tcx`
3. add tcx_sync
4. support `tcx` files upload to strava
=> feat: support tcx

requirements.txt, scripts/gpxtrackposter/track.py
fix #275 , Use `hr` instead of fixed index
=> fix: GPX heartrate parsing

Dockerfile, requirements.txt
1. fix bash error syntax
2. fix "garmin" typo
=> fix dockerfile build error

.vscode/settings.json, scripts/codoon_sync.py
1.Run` black .` to pass ci
2.delete `.vscode` folder
=> style: black format

scripts/tcx_to_strava_sync.py, scripts/utils.py
1. Fix: Some TCX files have no time objects in them will break the code
2. adjust: my testing showed that the code can upload 16 files before reaching the Strava API's 15-minute rate limit
=> Patch: 1. skip TCX with no time objects; 2, adjust waiting time

src/components/RunTable/RunRow.jsx, src/pages/index.jsx
=> fix:select multiple rows

src/utils/utils.js
1. hard fix data process `location_country` field contains `臺灣`
2. fix city and province regex ,must matched at least two words
PS: may do data cleaning at data sync is more better?
=> hard fix `location_country` contains `臺灣`

scripts/utils.py
=> fix: strava get last activites is wrong

requirements.txt, scripts/codoon_sync.py, scripts/utils.py
=> Add TCX to codoon_sync.py

scripts/codoon_sync.py
=> Elevation info support

src/components/RunMap/index.jsx, src/components/RunMap/style.module.scss, src/components/YearsStat/index.jsx, src/pages/index.jsx, src/utils/const.js
Add a fullscreen button for the map and resize the layout so that the site title occupies less space, allowing the map to be 100px higher.
=> feat: Add fullscreen button for map & resize layout

.gitignore, gatsby-config.js, package.json, src/pages/index.jsx
Signed-off-by: shaoanianche <github@duanfei.org>
=> chore:add vercel analytics

README-CN.md, README.md
=> share my Running page

README-CN.md, README.md
Add first-time strava data synchronization instructions to README.
=> chore: update README

src/components/RunTable/RunRow.jsx, src/components/RunTable/index.jsx, src/utils/utils.js
RunTime using `moving_time` from activity instead of `distance * pace`, also fix sorting
=> fix: RunTime using `moving_time`

README-CN.md, README.md, src/components/YearStat/index.jsx
- 添加了stevenash0822的跑步主页 (跑步小菜鸟一枚orz)
- 修改所有跑步记录的平均配速的计算规则 (yihong似乎是平均每一次跑步记录的配速来获得全局的平均配速，计算规则是否应该更正为总路程/总时长呢，因为每一次跑步的距离都不相等)
=> [PR] Add: stevenash0822 homepage & Update: calculation of avgPace

README-CN.md, README.md
1. 在README(EN/CN)中添加我的[跑步记录](https://vinton.store/Running/)
2. 在README(EN/CN)中去除这位朋友**haowei93**的多余“< >”。
3. 在README(CN)中补全这位朋友**hanpei**的App记录(他在README.md中填写的是Garmin-cn，在README-CN.md中是空白)。
=> doc: vint website

README-CN.md, README.md
Good Project! I have been following your work on it and greatly appreciate the valuable contributions you have made. I am writing to submit a pull request with a request to share my running page within the repository. Thanks!
=> :running: share muyids's running page

README-CN.md, README.md
安装这个项目过程中按readme安装12-14的版本报错，不清楚是否这里应该和package.json中的同步？开源新手，有误解多包含
=> readme中node版本修改

.github/workflows/run_data_sync.yml
=> Add sync strava data args comment: `--only-run`

README.md
add Echo's running page into readme
=> feat: add a new runner's page

.github/workflows/gh-pages.yml, .github/workflows/run_data_sync.yml, README-CN.md, README.md, package.json, run_page/data_to_csv.py, vite.config.ts
1. change default build name from `build` to `dist` for vercel default
2. change all the scripts to run_page
=> doc: fix v2.0 doc and actions change

.github/workflows/gh-pages.yml, .github/workflows/run_data_sync.yml
=> fix: fix wrong path in github action files

.github/workflows/run_data_sync.yml
=> fix typo in Github action configurations

src/utils/utils.ts
fix: #520 (cherry picked from commit 7c3c05b971c787cb1fa085d6c1552376227ea8a6)
=> fix: cityMatch #520

src/components/RunMap/index.tsx
add zoom in and zoom out button
=> style: add NavigationControl

src/components/RunTable/style.module.scss
=> perf: use auto instead of scroll

src/components/RunTable/RunRow.tsx, src/components/RunTable/index.tsx, src/components/RunTable/style.module.scss, src/pages/index.tsx, src/utils/utils.ts
[issues 122](https://github.com/yihong0618/running_page/issues/122)
RunRow deselect.
https://github.com/yihong0618/running_page/assets/85230052/764108eb-f68e-44d2-b017-bd12179dafbc
=> feat: `RunRow` toggle selection & cursor pointer

README-CN.md, README.md
=> docs: add runner page

src/components/RunTable/index.tsx
=> Update index.tsx 解决点击BPM不能排序的bug

run_page/codoon_sync.py, run_page/endomondo_sync.py, run_page/garmin_to_strava_sync.py, run_page/gpxtrackposter/circular_drawer.py, run_page/gpxtrackposter/grid_drawer.py, run_page/gpxtrackposter/poster.py, run_page/gpxtrackposter/track.py, run_page/gpxtrackposter/track_loader.py, run_page/gpxtrackposter/tracks_drawer.py, run_page/gpxtrackposter/utils.py, run_page/gpxtrackposter/value_range.py, run_page/gpxtrackposter/xy.py, run_page/gpxtrackposter/year_range.py, run_page/joyrun_sync.py
`tracks = loader.load_tracks(args.gpx_dir)`,  if load_tracks from dir ,missing a param file_suffix. 
```
➜  running_page git:(master) python3 run_page/gen_svg.py --gpx-dir ~/xxx/rides/shang_hai
Traceback (most recent call last):
File "/Users/xxx/xxx/running_page/run_page/gen_svg.py", line 262, in <module>
main()
File "/Users/xxx/xxx/running_page/run_page/gen_svg.py", line 211, in main
tracks = loader.load_tracks(args.gpx_dir)
TypeError: load_tracks() missing 1 required positional argument: 'file_suffix'
```
=> set default file_suffix = gpx

README.md
Thank you so much yihong0618! Have followed your twitter since twitter was still twitter.
Glad to join.
=> Request to add Yer1k's running page

src/utils/const.ts
https://github.com/yihong0618/running_page/issues/643#issuecomment-2042675730
> @yihong0618 @orionna319 看起來確實如 https://github.com/yihong0618/running_page/issues/643#issuecomment-2041976662 所說不用重構專案，但需要根據 https://github.com/yihong0618/running_page/issues/643#issuecomment-2042668580 更新`README.md` / 於`src/utils/const.ts`對應位置上新添加提示 command
只有添加 comment，沒有動`README.md`/`README-CN.md`（因為兩個`README.md`本來就不一致，不好更新）
=> docs: mapbox token

README-CN.md, README.md
=> docs: add runner

README-CN.md, README.md
This project is very interesting. Thank you for your contribution. I will apply to share my running data page. Thank you for your approval.
=> Add data to 'running page runners' table

README-CN.md, README.md
https://laqieer.github.io/running_page/
=> Add laqieer's running page to README

README.md
I add my runner's home page, thanks
=> add laihj's run page

.github/workflows/ci.yml, run_page/gpxtrackposter/exceptions.py
Failures: https://github.com/yihong0618/running_page/actions/runs/13105934639
Fixed: https://github.com/laqieer/running_page/actions/runs/13157008272
=> Fix CI format failure

run_page/coros_sync.py
fix https://github.com/yihong0618/running_page/issues/794
=> download all activities

run_page/keep_sync.py
keep数据字段变化 timestamp->unixTimestamp
=> fix: keep_sync.py

src/components/ActivityList/index.tsx
fix: use local date from activities and use ISO week calculation for Summary component
=> fix: use local date from activities and use ISO week calculation for Summary component

src/components/ActivityList/index.tsx
Simplify the part of calculating ISOWeek
=> fix: improve week calculation in ActivityList component

index.html, public/404.html, src/static/site-metadata.ts
add 404.html to implement redirect for compatible with SPA in Github Pages environment, and improve index.html script to handle redirect
fix #806
=> fix: add redirect handling in 404 page and improve index.html script for Github Pages

run_page/joyrun_sync.py
(Joyrun scope only)
fix below error and enhance the elevation gain calculation.
```log
File "/home/runner/work/running_page/running_page/run_page/joyrun_sync.py", line 366, in parse_raw_data_to_nametuple
altitude_list = eval(altitude_list) if altitude_list else None
^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'altitude_list' where it is not associated with a value
```
=> fix: replace HeartRateList with DataSeries for heart rate and elevation_gain in Joyrun

run_page/gpxtrackposter/track.py
The FIT file from garmin changed a bit. So the current version cannot load track info.
This PR fixed this bug.
=> [Urgent] Fix garmin route load failure 

README-CN.md, README.md, run_page/codoon_sync.py, run_page/endomondo_sync.py, run_page/generator/db.py, run_page/gpx_to_strava_sync.py, run_page/gpxtrackposter/github_drawer.py, run_page/keep_sync.py, run_page/nike_sync.py, run_page/tcx_to_strava_sync.py
=> fix: a few typos

run_page/gpxtrackposter/track.py
While I was figuring out how to generate my workouts page only with GPX files, I found the problem described in the title, so I fixed it :)
=> fix: only has 'run' sport type when syncing with GPX files

README-CN.md, README.md
According to [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint) Adjust the format of the README document and removed the duplicate description of the `PRIVACY_MODE` setting item in `README_CN.md`.
=> Markdown lint and remove duplicate PRIVACY_MODE setting description in README_CN

README.md
=> Update README.md, adding running page user JMGutiH

run_page/garmin_sync.py, run_page/gpxtrackposter/track.py
=> make garmin's tradmill data could be imported

run_page/keep_sync.py
Add mountaineering datatype in KEEP2STRAVA to support hiking data.
Previously, only "outdoor walk" was supported, but not "hiking."
=> Fix: support hiking data for keep (#861)

src/components/ActivityList/index.tsx, src/utils/const.ts
Resolves https://github.com/yihong0618/running_page/issues/874
Reference website https://run.zhengnq.com/summary
=> feat: elevation gain in summary

.github/workflows/ci.yml, README-CN.md, README.md, package.json, src/components/ActivityList/index.tsx, src/components/RunMap/index.tsx, src/utils/const.ts, src/utils/utils.ts
`prettier --write` This command formats all files without outputting errors, so it is always true
https://github.com/yihong0618/running_page/blob/master/package.json#L43
=> ci: fix nodejs lint not working

run_page/generator/db.py, src/components/RunTable/RunRow.tsx, src/utils/const.ts
- strava uses total_elevation_gain to count elevation 
- default display of elevation_gain data
=> fix: strava elevation gain no attribute

run_page/garmin_device_adaptor.py, run_page/garmin_sync.py
修复 “使用strava_to_garmin_sync.py同步原始fit格式心率展示异常” #910 
`Apple Watch`同步`Strava`时，其原始数据的心率是不连续的，如果连续几秒的心率没变化，只在心率有变化时的最后一秒记录一次。
`Record`往后查找第一条有效心率并填充空白`Record`，针对结束时无心率的场景往前查找
修改前
修改后
=> fix heart rate data with the nearest valid value

.gitignore, run_page/keep_to_strava_sync.py, run_page/strava_sync.py
fix https://github.com/yihong0618/running_page/issues/922 
本地运行测试通过。
测试结果：
=> 修复keep_to_strava_sync --sync-types running 出现其他运动类型数据的缺陷

run_page/generator/__init__.py, run_page/generator/db.py
- generator/__init__.py
- generator/db.py
=> fix: some file type warnings

run_page/codoon_sync.py
修复了Codoon导出tcx文件会发生KeyError的bug。
=> fix: empty data KeyError (https://github.com/yihong0618/running_page/issues/949)

src/components/ActivityList/index.tsx, src/components/ActivityList/style.module.css, src/components/RoutePreview/index.tsx, src/components/RoutePreview/style.module.css
=> feat: summay flipp in summary day

README-CN.md, README.md
修改了README和README_CN两个文档，增加了我的运动界面链接。
=> add new runner bolyn

.github/workflows/run_data_sync.yml
=> fix single quote syntax error

src/pages/index.tsx
=>  feat: support for canceling selection on total page.

src/hooks/useActivities.ts
=> add: standardizeCountryName, fix #997

run_page/codoon_sync.py
Codoon records for indoor activities contain valuable heart rate data but lack GPS track points. This commit enables exporting these activities specifically to the TCX format. TCX is chosen because it is designed to handle fitness data that may not include a GPS track, making it the ideal format for this use case.
=> feat(export): Add TCX support for Codoon activities without GPS data

src/components/ActivityList/index.tsx
summary第二个下拉框选择life限制第一个下拉框只能选择all
=> fix: summay选择life限制
